version: '3'
services:
  app:
    container_name: absen-go-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./.env:/app/.env